### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by PySimpleGUI** [eagleEggs/topanga#1]
Thank you SO much for the sponsorship.  It really means a lot coming from you.  Oh, and a belated thanks for a really nice looking theme too!  I use the "topanga" theme often.

It was really great seeing your name in the sponsor email this morning.  Big smiles today 😁

Hope you're doing well and that PySimpleGUI is working OK for your projects.

**Comment by eagleEggs** [comment]
Hey buddy! Thanks for the message and you're welcome. I had to pip install PySimpleGUI last night and I was like, let me see how that's going... When I noticed they do sponsors now on Github (I'd never noticed it before) I felt that all the benefits I get from PSG, the amount I use it, and knowing how hard you worked and continue to work on it - It was definitely well deserved and I wanted to show my support :)

Hope all is well also, and glad you like the theme! <3
