### ISSUE TITLE
Lining up the Text Elements in PySimpleGUI

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [eagleEggs/topanga#1]
I noticed in your screenshot that your Text elements are all of varying length and as a result are not lining up.

If you turn off autosize_text in your call to Window (was FlexForm), then they should all line up.

**Comment by eagleEggs** [comment]
So I'm doing sg.Window('Topanga', autosize_text=False) but it doesn't recognize autosize_text. Are you referring to that, or specifying it within the layout? Based on your arguments to Window in your other examples I'm best guessing that's where you mean :)

**Comment by MikeTheWatchGuy** [comment]
Right, autosize_text should make all of your text elements the same size

**Comment by MikeTheWatchGuy** [comment]
try setting `sg.Window('My window', autosize_text = False)`

The default is True.

**Comment by eagleEggs** [comment]
Perhaps that doesn't work with the way I'm laying this out?:

layout =  [[sg.T('                                                    Topanga ∩(^-^)∩')],
		  [sg.Text('')],
		  [sg.Text('General:')],
          [sg.Text('Browser Type (IE):  '), sg.InputText('IE')],
          [sg.Text('')],
          [sg.Text('Oracle:')],
          [sg.Text('Oracle Login Password:'), sg.InputText('')],
          [sg.Text('')],
          [sg.OK()],
          [sg.Cancel()],
          [sg.Text('                                     License GPLv3 | github.com/eagleEggs')]]

out= sg.Window("Topanga", autosize_text=False).LayoutAndRead(layout)


Exception:

Exception ignored in: <function Window.__del__ at 0x0000025B216C5AE8>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 2148, in __del__
    for row in self.Rows:
AttributeError: 'Window' object has no attribute 'Rows'
Traceback (most recent call last):
  File "C:\Users\User\topanga\topanga.py", line 322, in <module>
    out= sg.Window("Topanga", autosize_text=False).LayoutAndRead(layout)
TypeError: __init__() got an unexpected keyword argument 'autosize_text'

**Comment by eagleEggs** [comment]
But for now the GUI is not the priority but I appreciate your input. This GUI won't stay like this so once I get more focus on it and fancify it we'll find what's missing.

**Comment by MikeTheWatchGuy** [comment]
Sorry about the misinformation

auto_size_text

I figured you were using an IDE and could see the declarations and get suggestions.

What IDE are you using?


@mike<mailto:mike_barnett@hotmail.com>

**Comment by eagleEggs** [comment]
Haha makes sense. Yes autocomplete would have saved me here... But I turned the Python autocomplete addon off in Sublime Text as it was a bit buggy last week... Sweet.
