### ISSUE TITLE
Post screenshots on PySimpleGUI GitHub please!

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [eagleEggs/topanga#3]
I know you've got some really cool pages hidden in those tabs!  I and others would enjoy seeing them.  I would like to make you a bit of a poster child project because it's complex looking but yet simple.

Here's already an issue open for you to post in.
PLEASE .......

**Comment by eagleEggs** [comment]
Haha yes I like to keep things simple! Sure no problem. I don't see an issue for this though on PSG,

**Comment by MikeTheWatchGuy** [comment]
It's right here!  https://github.com/MikeTheWatchGuy/PySimpleGUI/issues/10

**Comment by eagleEggs** [comment]
Posted!

**Comment by MikeTheWatchGuy** [comment]
Thank you SOO much... and the other users thank you too.

You've already given me a lot of ideas of stuff to try.

GUIs are such a visual thing.  They have to be seen to be experienced and your GUI is one with experiencing!

This is some really advanced stuff... on every tab.  Like the notes tab.  Does it really save the notes to disk?  

What does the progress bar do btw?

If your testers don't go nuts then they're dead inside.

**Comment by eagleEggs** [comment]
Haha well thanks! Yes you type notes in there and then it saves to disk. The progress bar is meant for test cases. So, you would either choose to add it into single cases, or wrap it around all cases where the progress bar would increment each case just to easily see where you're at - Or both. Below that bar I'm also going to add some text that updates where you can write what it's doing at the time.

I'm working now on 'creating test cases from the GUI.' Which would be an interactive way to create it. Normally you have to go back and forth finding elements you want to click and such, script it out and run it, wait for result, redo until you get the right sequence etc... With this I should be able to grab all elements, highlight them and tag them with a number, translate those results into a log - where testers will cross reference that while typing in their test scripts - All in the GUI. Instead of the normal process, this wont crash if 'element not found', and you wont have to go back and forth between the browser, IDE, launching, waiting, etc... which will make it much more fluid and fast to build cases overall.

Not sure if that makes sense.

**Comment by MikeTheWatchGuy** [comment]
Yea, makes sense.

I made changes that stop crashes with Graph drawing.  Before I was crashing. Now I print an error.
I do print an error when the element is not found.  

Oh, hey, MAYBE I can return a "dummy" element when the element isn't found. Then when they try and update the dummy element I can print an error / warning!!

This will stop all those annoying crashes.

**Comment by eagleEggs** [comment]
Actually I don't see any errors with graph drawing from my tool to your examples. Is this a new issue?

**Comment by MikeTheWatchGuy** [comment]
The problem before was if you did not call Finalize and thus got back None as your Figure objects.  Now I simply check for None.  Try removing the finalize and you'll see what I mean.

I really am pondering return a "Default element" for searches that find nothing.
At the moment, this is all that happens:
            print('*** WARNING = FindElement did not find the key. Please check your key\'s spelling ***')

I still return None, which the caller will likely try and call update on.

**Comment by MikeTheWatchGuy** [comment]
How would you feel about receiving an "Error Element" back when you call FindElement?  I think that would actually be kinda cool
You can do things to it like try to Update it.  Oooo.... a Popup when you try to use it!

**Comment by MikeTheWatchGuy** [comment]
In Python you use constants you make up at enums.

Here is a partial list of Element's.  Note the new Error Element

**Comment by eagleEggs** [comment]
Oh yea, Finalize() to see graph - yep!

I'm thinking about this error element thing. Are you referring to dynamic layouts and such? Why would the code not know what elements are available? If dynamic, I could see receiving an element to populate while waiting for the expected element (if that's what the code does). And I suppose all there is right now is to try except the FindElement(), or if not FindElement()~

**Comment by MikeTheWatchGuy** [comment]
I’m coding example now… stay tuned…


@mike<mailto:mike_barnett@hotmail.com>

**Comment by MikeTheWatchGuy** [comment]
I made PyCharm "Live wrapper".  I type Ctrl+J and I see this menu:

![snap0379](https://user-images.githubusercontent.com/13696193/46264366-092aee80-c4ea-11e8-9e85-9df9e89af662.jpg)


If I choose the Simple layout this code instantly popps into my editor
![snap0380](https://user-images.githubusercontent.com/13696193/46264373-18aa3780-c4ea-11e8-8a24-907979d5e813.jpg)


And if I choose Persistent, this is pasted in

![snap0381](https://user-images.githubusercontent.com/13696193/46264377-2364cc80-c4ea-11e8-9b7b-0fc5647f1590.jpg)


It makes it SO nice to be able to jump ring to a GUI

**Comment by eagleEggs** [comment]
That is pretty cool! That definitely saves time. Hey - Why not make a GUI that creates GUI's - That way it's IDE agnostic. Hmmmmm

**Comment by MikeTheWatchGuy** [comment]
I made a nicer error message :-)

**Comment by MikeTheWatchGuy** [comment]
![snap0382](https://user-images.githubusercontent.com/13696193/46264601-d2a2a300-c4ec-11e8-8175-2ffa60020db5.jpg)

**Comment by MikeTheWatchGuy** [comment]
Yea, I've thought about a generator, editor, WYSIWYG, and even text based layout.

I did a LOT of work towards a text based one.  My parser was close to being done.  Then I realized that it was just as easy to write code and the code was just as readable as what I was doing in text.

Making a generator of some sort would be trivial.

We are all already making forms by using loops and generators.  

You should propose it as a good "beginner's next project" on Reddit when someone asks for what to do.

**Comment by eagleEggs** [comment]
LOL that error message.... But yea I totally agree about GUI building methods. I mean, it's two different purposes as well. Branching to a system like that would be a whole thing in itself... Believe me I was jokingly mentioning it!

**Comment by eagleEggs** [comment]
Wow so simple.... You can now build scripts within the GUI and run them in realtime :)

**Comment by MikeTheWatchGuy** [comment]
You can write code in a GUI window and run it?
hmmm

**Comment by eagleEggs** [comment]
Yup :) Exactly what I was planning! I'm about to commit it. It's pretty simple.

**Comment by eagleEggs** [comment]
Not sure if this has been done before... But I'm reverse passing class objects to a newly imported script to then control the base module >.< so cool

**Comment by MikeTheWatchGuy** [comment]
You can run right out of RAM too, right?  Run whatever vales[‘script’] is?


@mike<mailto:mike_barnett@hotmail.com>

**Comment by eagleEggs** [comment]
Not sure about RAM... I haven't noticed any issues. But by declaring an empty variable (testVar) in the second module, I assign the class to it after importing from the base module:

`instantiate_app = Github(values["browsertype"], values["appuri"],values["appname"], values["appun"], values["apppw"])
import Topanga_Scratch # this is the external module with a single line: testVar = "test"
Topanga_Scratch.this = instantiate_app`

Then in the GUI, I can use the scratch board to control it:

`print(testVar.appName)` # this overwrites the second module and executes it

Essentially anything you want to control, you need available vars in the second module, and then assign from the base module after importing the second module.

**Comment by MikeTheWatchGuy** [comment]
> Basically just taking Multiline and piping it into a new .py file, importing that, reimporting if it's already been imported. Executes on import. But it's cool because you can basically script anything there and control the base application :)
> 
> Yes the Scratchboard tab.

You can use the exec command to run whatever is entered.
`exec(values['multiline'])`

**Comment by eagleEggs** [comment]
That executes in the current context of the running module? Like if I already have class objects created, can I call them with exec or does that spawn a new execution outside of the base module?
