### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [eagleEggs/topanga#4]
I love the new badges! LOL you're funny.

You support more than Python 3.7 however, right?  If you want to say that it's written using Python 3.7, then maybe have an "Authored using 3.7" badge?  Otherwise it looks like you only support 3.7.

**Comment by eagleEggs** [comment]
True thanks for pointing that out, let me change that!

**Comment by eagleEggs** [comment]
Aside from that I really need to make readme's look better. Never been my forte'
